### ISSUE TITLE
Can you fix regression bug in IOS for grid columns?

### ISSUE THREAD

**Issue by ne0rrmatrix** [jerry08/Woka#1]
Hi. Can you add a fix for grid layout in IOS? It is currently broken when setting Auto for for grid column in IOS. Fixed in 8.0 but not back ported to 7 succesfully. Current workaround is to set ```<MauiVersion>7.0.81</MauiVersion>```
If you can add that it would be much appreciated. I have no idea how to fix that?

**Comment by jerry08** [comment]
Do you have a link to the issue (or issue number) in MAUI repo? I can try to fix it but I won't be able to test it since I don't have an iOS device.

**Comment by ne0rrmatrix** [comment]
Here is link to fix in Maui itself if that helps [https://github.com/dotnet/maui/pull/15143/files](https://github.com/dotnet/maui/pull/15143/files)

Here is link to issue: [https://github.com/dotnet/maui/issues/15018](https://github.com/dotnet/maui/issues/15018)

**Comment by jerry08** [comment]
Seems feasible. I'll add the fixes to this project after my work.

**Comment by jerry08** [comment]
I posted an update which might fix the issue. (I haven't tested it though.) You can refer to [this](https://github.com/jerry08/Woka/#special-cases) to see the usage.
