### ISSUE TITLE
RefreshView on IOS and MAC cause shift to right of CollectionView items

### ISSUE THREAD

**Issue by ne0rrmatrix** [jerry08/Woka#6]
When wrapping a CollectioView inside a RefreshView all the contents get shifted to the right nearly off screen. This is fixed in all betas for dotnet 8.x It has not been back ported to Net 7.x as of yet. [https://github.com/dotnet/maui/issues/7315](https://github.com/dotnet/maui/issues/7315)

<img width="438" alt="172458679-bd490386-d3a3-467c-9b4a-8797b6601caf" src="https://github.com/jerry08/Woka/assets/4167863/492e9fb4-331a-495f-95e4-1b2e8e1cfc11">

Here is a link to fix for Maui. https://github.com/dotnet/maui/pull/14302
If you can find the time to add a fix that would be awesome. I spent about 10 hours or so trying myself. Still can't figure out how you do it. Maybe after another year of learning and building stuff I will be able to understand how this all works. Fingers crossed. Till then Jerry is the solution, I hope :)

**Comment by marcos-correa** [comment]
Any workaround to fix this?
